name: hw-github-actions

on:
  pull_request:
    branches:
      - main

jobs:
  frontend-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run:
          npm ci
      - name: Angular Full CI
        uses: colbyhill21/angular-full-ci/@v1.0
        with:
          testcommand: run test
          mocha: true

